# app/cache.py
# Lightweight in-memory caching utility used by the service layer.
# This module provides a simple TTL-based cache to avoid repeated calls
# to external data sources (e.g., yfinance). It improves performance,
# reduces external API load, and avoids rate limiting.

from cachetools import TTLCache
from typing import Any, Tuple

# ------------------------------------------------------------------------------
# Cache Configuration
# ------------------------------------------------------------------------------
# TTLCache provides a dictionary-like object with:
#   - Time-based expiration (TTL = Time To Live)
#   - Automatic removal of expired entries
#   - A maximum size to prevent unbounded memory usage
#
# Parameters:
#   maxsize = 256   → Cache up to 256 distinct queries
#   ttl = 300       → Each entry lives for 300 seconds (5 minutes)
#
# Rationale:
#   - Stock price statistics do not need per-request freshness.
#   - Repeated queries for the same ticker/date range should be served fast.
#   - A 5-minute TTL provides a good balance between freshness and performance.
#
# This cache is per-process (in-memory). For distributed deployments,
# a shared cache (e.g., Redis) would be recommended.
# ------------------------------------------------------------------------------
_cache = TTLCache(maxsize=256, ttl=300)


def make_key(*parts: Any) -> Tuple[Any, ...]:
    """
    Construct a consistent cache key from arbitrary components.

    Args:
        parts: Values that uniquely identify a cached computation.
               Example components:
                   - endpoint name (e.g., "stats")
                   - ticker symbol
                   - start date (ISO string)
                   - end date (ISO string)

    Returns:
        A tuple containing the parts. Tuples are hashable and can be used
        as dictionary keys in TTLCache.

    Example:
        key = make_key("stats", "MSFT", "2024-01-01", "2024-12-31")
    """
    return tuple(parts)


def get(key: Tuple[Any, ...]) -> Any:
    """
    Retrieve a cached value if it exists and has not expired.

    Args:
        key: The tuple key generated by make_key().

    Returns:
        The cached value if present and valid; otherwise None.

    Notes:
        - TTLCache returns None for missing keys, matching our expected behavior.
        - If the entry has expired, TTLCache automatically removes it and returns None.
    """
    return _cache.get(key)


def set_(key: Tuple[Any, ...], value: Any) -> None:
    """
    Store a value in the cache.

    Args:
        key: Cache key created by make_key().
        value: Any computed result you want to reuse later (usually StatsResponse).

    Behavior:
        - If the cache is full (> maxsize), the oldest entry is evicted.
        - Each stored value begins a new TTL countdown (5 minutes by default).

    Example:
        set_(key, stats_response_object)
    """
    _cache[key] = value

def clear() -> None:
    """Clear all entries in the in-memory cache. Test helper."""
    _cache.clear()
